[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lock_fund = "9brXu1LNCURaR8bde1ekTueEnafQ1nHDn1Y2BTfzCKyK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./scripts/keys/authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
